FROM denoland/deno:alpine

# Setup Environment
WORKDIR /app
ENV NODE_ENV=production

# Copy Project Source Code  
COPY deno.json* deno.lock* ./
COPY . .

# Building
RUN  deno task install 

# Service Start 
CMD ["deno", "task", "serve"]

# Listens Serve  Port
EXPOSE 8085
