FROM denoland/deno:alpine

# Setup Environment
WORKDIR /app
ENV NODE_ENV=production

# 時區
ENV TZ=Asia/Taipei
RUN echo "${TZ}" > /etc/timezone
RUN ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime

# Install & Update package
RUN apk update \
    apk upgrade --no-cache \
    apk add --no-cache icu-data-full tzdata libstdc++

# Copy Project Source Code  
COPY deno.json* deno.lock* ./
COPY . .

# Building
RUN  deno task install 

# Service Start 
CMD ["deno", "task", "serve"]
