# 基於的映像檔
FROM node:current-alpine

# 建立工作目錄
WORKDIR /usr/src/app

# 時區
ENV TZ=Asia/Taipei
RUN echo "${TZ}" > /etc/timezone 
RUN ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime 

# 安裝&更新所需的套件
RUN apk update \
    apk upgrade --no-cache \
    apk add --no-cache icu-data-full tzdata

# 把目錄下的程式碼直接復制到容器中
COPY package*.json ./
RUN npm install 
COPY . .

# 指定使用的端口
EXPOSE 3095
EXPOSE 3094 

# 容器啟動時
CMD [ "npm", "start" ]
